[package]
name = "gantry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5"
tracing = "0.1"
tracing-subscriber = "0.2"
actix-web = "3"
serde = "1.0"
serde_json = "1.0"
